paths:
  /product:
    get:
      tags:
        - Products
      summary: Gets All Products from the DB
      responses:
        "200":
          description: Products fetched successfully from the DB
          content:
            application/json:
              schema:
                $ref: "#components/schemas/ProductsResponse"
        "500":
          description: Internal Server Error
    post:
      tags:
        - Products
      summary: Add a new product to DB
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/AddProductPayload"
      responses:
        "200":
          description: Product added successfully
          content:
            application/json:
              schema:
                $ref: "#components/schemas/NewProductResponse"
        "400":
          description: Wrong params
        "500":
          description: Internal Server Error

  /product/realtimeproductsUser:
    get:
      tags:
        - Products
      summary: Gets view of user product options
      responses:
        "200":
          description: Success
        "500":
          description: Cannot GET products

  /product/realtimeproductsAdmin:
    get:
      tags:
        - Products
      summary: Gets view of admin or premium product options
      responses:
        "200":
          description: Success
        "500":
          description: Cannot GET products

  /product/{productId}:
    get:
      tags:
        - Products
      summary: Gets a single product by its id
      parameters:
        - name: productId
          in: path
          required: true
          description: Product id to fetch
          schema:
            $type: string
      responses:
        "200":
          description: Product from DB with the given productId
          content:
            application/json:
              schema:
                $ref: "#components/schemas/ProductResponse"
        "404":
          description: Product with given productId Not Found
        "500":
          description: Internal server error
    put:
      tags:
        - Products
      summary: Updates a single product for a given productId
      parameters:
        - name: productId
          in: path
          required: true
          description: Product id to fetch
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/UpdateProductPayload"
      responses:
        "200":
          description: Updated product with a given productId
          content:
            application/json:
              schema:
                $ref: "#components/schemas/ProductResponse"
        "400":
          description: Invalid body format.
        "404":
          description: User with given productId Not Found
        "500":
          description: Internal Server Error
    delete:
      tags:
        - Products
      summary: Deletes a single product by its id
      parameters:
        - name: productId
          in: path
          required: true
          description: Product id to fetch
          schema:
            $type: string
      responses:
        "200":
          description: Deleted product from DB with the given productId
        "404":
          description: Product with given productId Not Found
        "500":
          description: Internal server error

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Autogenerated MongoDB ID
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product description
        price:
          type: number
          description: Product price
        thumbnail:
          type: string
          description: Product thumbnail
        code:
          type: number
          description: Product code (unique)
        stock:
          type: number
          description: Product stock
        owner:
          type: string
          description: Product owner
      example:
        _id: ObjectId(64b828915ae2b63b11f48600)
        title: "Café Italiano"
        description: "Intensidad fuerte"
        price: 1500
        thumbnail: "https://img.freepik.com/psd-premium/bolsa-papel-maqueta-cafe_23-214888…"
        code: 3
        stock: 10
        owner: "Administrador"

    ProductsResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, error]
          description: Products response status
        payload:
          type: array
          description: Products array list
          items:
            $ref: "#components/schemas/Product"

    ProductResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, error]
          description: Products response status
        payload:
          $ref: "#components/schemas/Product"

    NewProductResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, error]
          description: Products response status
        payload:
          type: ObjectId
          description: Added Product ObjectId
        example:
          status: success
          payload: ObjectId(64b828915ae2b63b11f48666)

  requestBodies:
    UpdateProductPayload:
      type: object
      properties:
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product description
        price:
          type: number
          description: Product price
        thumbnail:
          type: string
          description: Product thumbnail
        code:
          type: number
          description: Product code (unique)
        stock:
          type: number
          description: Product stock
      example:
        title: "Café Italiano"
        description: "Intensidad fuerte"
        price: 1500
        thumbnail: "https://img.freepik.com/psd-premium/bolsa-papel-maqueta-cafe_23-214888…"
        code: 3
        stock: 10

requestBodies:
  AddProductPayload:
    type: object
    properties:
      title:
        type: string
        description: Product title
      description:
        type: string
        description: Product description
      price:
        type: number
        description: Product price
      thumbnail:
        type: string
        description: Product thumbnail
      code:
        type: number
        description: Product code (unique)
      stock:
        type: number
        description: Product stock
    example:
      title: "Café Italiano"
      description: "Intensidad fuerte"
      price: 1500
      thumbnail: "https://img.freepik.com/psd-premium/bolsa-papel-maqueta-cafe_23-214888…"
      code: 3
      stock: 10
